---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.255.13/30
    enp0s9:
      addresses:
      - 192.168.57.2/24
    enp0s19:
      addresses:
      - 192.168.56.15/24
